### ISSUE TITLE
Incomplete word mapping.

### ISSUE THREAD

**Issue by Nivek92** [cerisara/DialogSentimentMastodon#1]
Hey,
I constructed a word mapping using the datatrainJoint.idx and datatrainJoint.txt (mapping each number in datatrainJoint.idx to the corresponding word in datatrainJoint.txt) so I can construct a 
datatestJoint.txt from the datatestJoint.idx (here are also a few contradictions e.g. one time AnonNameT and AnonNameR mapping to the same id but for now I just use the first occurence as correct mapping)

During that process I noticed that every single line in datatestJoint.idx is missing a mapping for at least 1 word often even more than 1.

I wonder what I am doing wrong.

**Comment by cerisara** [comment]
Hi,
sorry for answering so late, I don't have any email notifications where there's a message - because my mailbox is too full- so I've only seen your issue now.

You've done nothing wrong: mapping indexes to words is still incomplete for the test set, because I haven't had time so far to anonymize the test set. But you may still run the experiments with the test indexes, and you may still access the training text (that has been anonymized). Every anon* should map to the same anonymized word (so you're right, there's a small bug there, although it shouldn't impact the results).

Sorry for this. Hopefully, I'll have some time to make all this cleaner.

**Comment by cerisara** [comment]
OK, the test corpus has been anonymized and posted. The mapping between words and word_indexes may still not be fully one-to-one, because of anonymization, but it shouldn't pose any big issue: the same anon word may actually be mapped to several indexes, but you may either collapse them all onto a single index, or conversely (and this will reproduce the paper results), correspondingly duplicate the anon word forms onto as many word indexes.

I'll try and do it later on.
